# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alitzel Villanueva
email: alitzelvillanueva@ucsb.edu
description: >- # this means to ignore newlines until "baseurl:"
  Professional website to share more about myself.
github_username: alitzelvillanueva
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  avatar : "/assets/images/IMG_6073.jpeg"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.hofmannlab.com/people/alitzel-villanueva"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alitzelvillanueva"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/axvillanueva"
      
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alitzelvillanueva"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/axvillanueva"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
       author_profile: false
  header:
  image: /assets/images/image.png

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
